# Generated by Django 6.0.5 on 2026-06-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_id", models.IntegerField(db_index=True)),
                ("user_id", models.IntegerField(db_index=True)),
                ("username", models.CharField(blank=True, max_length=150)),
                ("role", models.CharField(blank=True, max_length=20)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("is_sharing", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("booking_id", "user_id")},
            },
        ),
    ]
