# Generated by Django 6.0.5 on 2026-06-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_service_image_db_storage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["-is_featured", "-created_at"]},
        ),
        migrations.AddField(
            model_name="service",
            name="featured_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
