# Generated by Django 6.0.5 on 2026-06-05 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.IntegerField(db_index=True)),
                ("client_username", models.CharField(max_length=150)),
                ("client_email", models.EmailField(blank=True, max_length=254)),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        help_text="Describe the job in detail — what needs to be done, any special requirements."
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        blank=True,
                        help_text="Type of service needed (e.g. Plumbing, Cleaning).",
                        max_length=100,
                    ),
                ),
                (
                    "skills_required",
                    models.TextField(
                        blank=True,
                        help_text="Specific skills or tools the provider should have.",
                    ),
                ),
                (
                    "duration_estimate",
                    models.CharField(
                        blank=True,
                        help_text="Estimated time to complete (e.g. '2 hours', 'half a day', '3 days').",
                        max_length=100,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Full address or neighbourhood where the job takes place.",
                        max_length=255,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "budget_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed price"),
                            ("negotiable", "Negotiable"),
                        ],
                        default="negotiable",
                        max_length=12,
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True,
                        help_text="Latest date by which the job should be completed.",
                        null=True,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Low — flexible timing"),
                            ("normal", "Normal"),
                            ("urgent", "Urgent — ASAP"),
                        ],
                        default="normal",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("taken", "Taken"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=12,
                    ),
                ),
                ("booking_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Job auto-expires and disappears from listings after this datetime.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider_user_id", models.IntegerField(db_index=True)),
                ("provider_username", models.CharField(max_length=150)),
                ("provider_email", models.EmailField(blank=True, max_length=254)),
                (
                    "cover_message",
                    models.TextField(
                        help_text="Explain your experience and why you're the right person for this job."
                    ),
                ),
                (
                    "proposed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Your price quote for this job (leave blank if you want to discuss).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "availability_note",
                    models.CharField(
                        blank=True,
                        help_text="When can you start or complete this job? (e.g. 'Available this weekend')",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.jobpost",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("job", "provider_user_id")},
            },
        ),
    ]
