# Generated by Django 6.0.5 on 2026-06-05 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_id", models.IntegerField(db_index=True, unique=True)),
                ("client_id", models.IntegerField(db_index=True)),
                ("client_username", models.CharField(blank=True, max_length=150)),
                ("service_id", models.IntegerField(db_index=True)),
                ("service_title", models.CharField(blank=True, max_length=255)),
                ("provider_id", models.IntegerField(db_index=True)),
                ("provider_user_id", models.IntegerField(db_index=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
