# Generated by Django 6.0.5 on 2026-06-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.IntegerField(db_index=True)),
                ("client_email", models.EmailField(blank=True, max_length=254)),
                ("client_username", models.CharField(blank=True, max_length=150)),
                ("service_id", models.IntegerField(db_index=True)),
                ("service_title", models.CharField(blank=True, max_length=255)),
                ("provider_id", models.IntegerField(db_index=True)),
                ("provider_user_id", models.IntegerField(db_index=True)),
                ("provider_email", models.EmailField(blank=True, max_length=254)),
                ("provider_username", models.CharField(blank=True, max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
