# Generated by Django 6.0.5 on 2026-06-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_id", models.IntegerField(db_index=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("booking_created", "New Booking Request"),
                            ("booking_confirmed", "Booking Confirmed"),
                            ("booking_rejected", "Booking Rejected"),
                            ("booking_cancelled", "Booking Cancelled"),
                            ("booking_in_progress", "Service In Progress"),
                            ("booking_completed", "Booking Completed"),
                            ("review_received", "New Review Received"),
                            ("payment_received", "Payment Received"),
                            ("payment_refunded", "Payment Refunded"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "booking_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
